### ISSUE TITLE
Build issues - entry file location

### ISSUE THREAD

**Issue by jacobcoro** [malte-j/y-op-sqlite#1]
Hi there! Thanks for making this!
Was excited to try this so I could use yjs in react-native. I was looking to directly polyfill my use of y-indexeddb with this. 
Unfortunately it doesn't seem to be working. 
First off there is no entry file. The files specified in the package.json don't exist. Looks like you forgot to add a build step to your pre-publish
![image](https://github.com/malte-j/y-op-sqlite/assets/52448067/05d1e92e-3553-4681-899e-5051ec1598b2)

I ran the build script and it built the files into a `dist` folder. So if you want to keep that behavior, you'll need to update the "main" and "module" path to "./dist/-y-op-sqlite.cjs", and the "types" as well.
I manually adjusted these in my project to get it pointing at the right file but it still didn't work.
Got these errors: 
![image](https://github.com/malte-j/y-op-sqlite/assets/52448067/e28f73f8-a2ba-43bb-9874-5af2d274f3ec)
yjs already imported - you might need to mark that as a peer dependency and let people bring their own yjs so it is not imported twice (i import it in another library I need)
The `getEnforcing` error seems to be some kind of build error. Maybe we are missing the OPSQLite dep?:
![image](https://github.com/malte-j/y-op-sqlite/assets/52448067/0f32aaa4-1d02-4d9f-b43e-4031d3515138)

Let me know if I can help more. I'm an experienced TypeScript and React dev but new to react-native so these build issues are a bit beyond me.
Cheers!

**Comment by malte-j** [comment]
Thanks for the report and sorry for the late reply. I think I published from the wrong folder, it should be fine now, at least it's working for me again. Can you update to ^1.0.7 and check if it works for you too, as I've not gotten the `getEnforcing` error before.
